### ISSUE TITLE
how to compile

### ISSUE THREAD

**Issue by OmriOn** [AlekseyMartynov/shazam-for-real#2]

**Comment by MABMW** [comment]
It is something easy, you just need, dotnet installed on the system, 
in my case, I have .NET6, 
but originally the project is for .Net2.1. 
But modifying the project's .csproj file is enough.

Then ensure that the nuget packages are installed, 
"Crc32.NET", "MathNet.Numerics", 
"NAudio", "Newtonsoft.Json"

now clone the repository on your local disk, 
and run the "dotnet build" command for the build.
